apiVersion : apps/v1
kind: Deployment
metadata:
  name: kweb1 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kweb1
  template:
    metadata:
      labels:
        app: kweb1 
    spec:
      containers:
        - name: kweb1 
          image: webdevops.azurecr.io/kweb1
          ports:
          - containerPort: 80